version: "2"
services:
  app: &app
    build:
      context: .
      dockerfile: ./Dockerfile
    stdin_open: true
    tty: true
    privileged: true
    command: >
      /bin/bash -c "
        rm -rf tmp/pids/server.pid &&
        bundle exec rails db:migrate &&
        bundle exec rails s -u webrick -p 3000 -b '0.0.0.0'
        "
    ports:
      - "80:3000"
